# Generated by Django 6.0.2 on 2026-02-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alert_emergency_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="severity",
            field=models.CharField(default="medium", max_length=20),
        ),
    ]
