# Generated by Django 6.0.3 on 2026-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='route_info',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='severity',
        ),
        migrations.AddField(
            model_name='alert',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='emergency_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=10),
        ),
    ]
