# Generated by Django 6.0.3 on 2026-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_remove_alert_route_info_remove_alert_severity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='proof_image',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_latitude',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_longitude',
        ),
        migrations.AddField(
            model_name='alert',
            name='route_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='emergency_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
