# Generated by Django 6.0.3 on 2026-03-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_remove_alert_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
