# Generated by Django 6.0.3 on 2026-03-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_proof_image_alert_resolved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='resolved_latitude',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_longitude',
        ),
    ]
